plasma-group/pigi

- package.json
- yarn.lock
Fixes #110
Pins ts-node version to 8.0.3
> Use ts-node 8.0.2 to fix #110

- packages/contracts/package.json
- packages/core/package.json
- packages/core/test/ethereum.ts
- packages/operator/package.json
- packages/plasma-js/package.json
- packages/types/package.json
- packages/types/types/ganache-cli/index.d.ts
- packages/utils/package.json
- packages/verifier/package.json
- packages/vyper-js/package.json
Just tried to run the project locally and got a few errors when running the NPM scripts. This PR should fix those and allow the project to be built and linted locally.
> Fix build, lint and fix commands

- packages/core/README.md
Fixes #29 
Just some minor updates to the README to link out to the correct contributing guide and remove anything that broke.
> Update core docs for TS refactor

- packages/contracts/src/contracts/PlasmaRegistry.vy
Made some minor cleanup changes to `PlasmaRegistry`. Mainly added some comments, docstrings, and used `__init__` instead of a separate initialization function. Also added a mapping of `name => address` so we can easily query the registry instead of looking at events!
> Cleaned up PlasmaRegistry.vy

- packages/docs/src/pg/src/specs/generalized-plasma-state.rst
Add missing code block closing quotes
> Add missing code block closing quotes

- packages/plasma-js/package.json
- packages/plasma-js/src/providers/base.provider.ts
- packages/plasma-js/src/providers/http.provider.ts
- packages/plasma-js/src/providers/index.ts
- packages/plasma-js/src/wrappers/base.wrapper.ts
- yarn.lock
Fixes #16, #12, #17, #14 
Relatively basic PR. Just started porting over `plasma-js-lib`. Simplified a lot of the files in `plasma-js-lib`.
> Started porting plasma-js

- packages/core/src/app/common/db/db.ts
- packages/core/src/app/common/db/key/types.ts
- packages/core/src/app/common/utils/codec.ts
- packages/core/src/app/common/utils/index.ts
- packages/core/src/app/common/utils/misc.ts
- packages/core/src/app/pg-core/db/chain-db.ts
- packages/core/src/app/pg-core/state/history-manager.process.ts
- packages/core/src/app/pg-core/state/history-manager.ts
- packages/core/src/interfaces/common/db/db.interface.ts
- packages/core/src/interfaces/common/utils/state.interface.ts
- packages/core/src/interfaces/pg-core/db/chain-db.interface.ts
- packages/core/src/interfaces/pg-core/state/history-manager.interface.ts
Fixes #28, 60
Adds proof generation logic to `HistoryManager`. Adds lots of methods to `ChainDB` to support proof generation.
This is a WIP and needs to be heavily tested!
> Added basic proof generation and supporting methods

- packages/docs/src/vyper-js/src/vyper-js/index.rst
Fixes https://github.com/plasma-group/pigi/issues/184
Adding documentation for vyper-js
> Adding vyper-js docs

- packages/contracts/package.json
Fixes broken build caused by PR #199 
The build script for contracts package was missing `waffle` build.
> Fix broken travis build

- packages/docs/src/spec/src/02-contracts/transaction-based-predicate.rst
> Typo fixed ;)

- packages/docs/src/spec/src/02-contracts/limbo-exit-predicate.rst
`StateUpdatee` to `StateUpdate`
> Typo fixed 2

- packages/docs/src/spec/src/01-core/merkle-interval-tree.rst
Fixes duplicate numbers, broken enumeration.
> Fixes nested enumerated list

- packages/docs/src/spec/src/01-core/merkle-interval-tree.rst
Fixes nested enumerated lists.
> Fixes nested enumerated lists

- packages/docs/src/spec/src/01-core/state-system.rst
Minor grammar fixes in Generalized State System
> Minor grammar fixes - Generalized State System

- packages/docs/src/spec/src/02-contracts/deposit-contract.rst
Minor fixes in Deposit Contract
> Minor fixes in Deposit Contract

- packages/docs/src/spec/src/01-core/double-layer-tree.rst
Minor fixes to Double Layer Tree
> Minor fixes to Double Layer Tree

- packages/docs/src/spec/src/01-core/merkle-interval-tree.rst
Minor grammar fixes to Merkle Interval Tree
> Minor grammar fixes to Merkle Interval Tree

- packages/docs/src/spec/src/02-contracts/deposit-contract.rst
Adds missing field (ID) to state object
> Adds missing field (ID) to state object

- README.md
- packages/contracts/README.md
- packages/operator/README.md
- packages/predicates/README.md
- packages/types/tsconfig.json
- packages/utils/README.md
- packages/vyper-js/README.md
- packages/watch-eth/README.md
Cleaned up various issues spotted by Codacy.
> Fixed various code quality issues

- packages/core/src/app/client/rpc-error-messages.ts
- packages/core/src/app/common/net/rpc/json-rpc/index.ts
- packages/core/src/app/common/net/rpc/json-rpc/json-rpc-client.ts
- packages/core/src/app/common/net/rpc/json-rpc/json-rpc-server.ts
- packages/core/src/app/core/net/index.ts
- packages/core/src/app/core/net/rpc-server.process.ts
Tackling a few issues on our docket, decided to clean up RPC server and client. Moves `JsonRpcServer` to sit next to `JsonRpcClient`. Added client error codes.
- Fixes #257 
- Fixes #258 
- Fixes #264
> Cleaned up old RPC server/client implementations

- packages/core/package.json
- packages/core/tsconfig.json
- packages/core/tslint.json
- yarn.lock
Added fancy TypeScript path aliases so we can use `~app/whatever` instead of `../../../app/whatever`
> Added TypeScript path aliases

- README.md
> Fixes link in readme

- package.json
- packages/contracts/test/Deposit.spec.ts
- packages/core/test/app/keystore/wallet.spec.ts
Increases test timeouts where necessary to prevent sporadic timeout failures.
> Fixing test timeouts

- packages/core/src/types/ovm/decider.interface.ts
- packages/core/src/types/ovm/quantifier.interface.ts
Adds base interfaces for OVM components. Concrete implementations and tests to come in later PRs.
- Fixes #331
> Adding Base OVM interfaces defining the core components

- packages/docs/src/pg/src/specs/generalized-plasma-state.rst
- Fix some wrong indentations in the spec doc.
- [o ] I have read and understood the [Plasma Group Contributing Guide and Code of Conduct](https://github.com/plasma-group/pigi/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.
> Fix wrong indent

- packages/core/src/app/ovm/deciders/equality-decider.ts
- packages/core/src/app/ovm/deciders/index.ts
- packages/core/src/app/utils/equals.ts
- packages/core/test/app/ovm/deciders/equality-decider.spec.ts
Implements a simple EqualityDecider checking if all passed in values are equal as well as a number of different test cases for it.
- Fixes #389
> Adding EqualityDecider

- .gitignore
- package.json
- packages/core/src/app/block-production/merkle-tree.ts
- packages/core/src/app/db/db.ts
- packages/example-rollup/index.ts
- packages/example-rollup/package.json
- packages/example-rollup/src/mock-aggregator.ts
- yarn.lock
Making it so LevelDB works, changing website to create and save a wallet if one does not exist in browser storage but reuse the wallet in storage if one exists
- Fixes #462
> Fixing LevelDB

- packages/example-rollup/runAggregator.sh
Makes aggregator log to a file as well as the console.
> Make Aggregator log to file (and console)

- packages/core/src/app/utils/misc.ts
- packages/example-rollup/src/mock-aggregator.ts
- packages/wallet/package.json
- packages/wallet/src/aggregator/aggregator-server.ts
- packages/wallet/src/aggregator/index.ts
- packages/wallet/src/aggregator/rollup-aggregator.ts
- packages/wallet/src/default-rollup-block-submitter.ts
- packages/wallet/src/index.ts
- packages/wallet/src/types/errors.ts
- packages/wallet/src/types/index.ts
- packages/wallet/src/types/rollup-block-submitter.interface.ts
- packages/wallet/src/types/unipig-aggregator.ts
- packages/wallet/test/client-aggregator-integration.spec.ts
- packages/wallet/test/helpers.ts
- packages/wallet/test/rollup-aggregator.spec.ts
- packages/wallet/test/rollup-block-submitter.spec.ts
- packages/watch-eth/src/ethereum-block-processor.ts
- packages/watch-eth/src/ethereum-event-processor.ts
- packages/watch-eth/src/interfaces/listener.ts
- packages/watch-eth/test/ethereum-block-processor.spec.ts
- packages/watch-eth/test/ethereum-event-processor.spec.ts
- packages/watch-eth/test/utils.ts
Handling events in aggregator
- Created an AggregatorServer class to separate the  networking from the logic
- Created a BlockSubmitter class to handle block queueing and submission
- Made Aggregator pass new block events to block submitter
- Made Aggregator survive restarts and added re-initialization tests
- Made BlockSubmitter survive restarts 
- Added BlockSubmitter tests for all functionality and restarts
Also:
- Made Aggregator survive restarts and added tests for it
- Fixes #452 
- Fixes #464 
- Fixes #465 
- Fixes #475
> Handling Events in Aggregator

- packages/wallet/src/aggregator/rollup-aggregator.ts
- packages/wallet/test/aggregator/rollup-aggregator.spec.ts
Disables time-based submission of empty blocks
> making it so that we do not submit empty blocks

- packages/example-rollup/config/unipig-genesis-state.json
Fixes addresses that were updated with 30 -> 3000 balance update.
> fixing balance addresses

- packages/wallet/src/rollup-state-machine.ts
Fixing issue reading from DB in RollupStateMachine. Small base-10 vs base-16 issue.
> fixing number parsing in RSM

- package.json
- packages/contracts/package.json
- packages/core/package.json
- packages/docs/package.json
- packages/example-rollup/package.json
- packages/prettier-config/package.json
- packages/types/package.json
- packages/wallet/package.json
- packages/watch-eth/package.json
- yarn.lock
This PR:
1. Syncs up all of the package numbers
2. Changes npm build output to include all `*.js` files
- Fixes #527
> Update NPM version numbers 

- packages/core/src/app/block-production/merkle-tree.ts
- packages/example-rollup/runAggregator.sh
- packages/example-rollup/src/mock-aggregator.ts
- packages/wallet/runValidator.sh
- packages/wallet/src/rollup-state-machine.ts
- packages/wallet/src/validator/rollup-fraud-guard.ts
- packages/wallet/src/validator/rollup-state-validator.ts
Fixes validator hex/decimal issue with slot calculation that was causing it to report fraud when transactions were not fraudulent. 
Also adds more logging for insight into validation and Merkle tree operations.
- Fixes #540
> Fix Validator From Reporting False Positives
